### ISSUE TITLE
problem with code.

### ISSUE THREAD

**Issue by cookedlizard** [grzegorz914/homebridge-meraki-control#4]
ReferenceError: fsPromises is not defined
    at new merakiDevice (/homebridge/node_modules/homebridge-meraki-control/index.js:103:7)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-meraki-control/index.js:40:11)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)

**Comment by cookedlizard** [comment]
Thanks looks like home bridge was installing the wrong version, I got it to pull the right one and that error is gone.
