### ISSUE TITLE
A client not in the meraki dashboard will halt the loading of the other clients

### ISSUE THREAD

**Issue by magic7s** [grzegorz914/homebridge-meraki-control#9]
Using `homebridge-meraki-control v0.10.5`

If I add a client that is not in the meraki dashboard, because it has not been on the network recently, the loading of all the other clients stops. All other Accessories show `No Response` in Homekit until the offline device is removed. 

It should be reproducible by added a fake mac address and receiving a 404 error from the meraki api, like the below.

Changing `"mode": false` for the client that is not online seems to avoid the issue. 

```
[27/09/2021, 10:32:05] [Meraki] Network: Meraki Network, dashboardClientsPolicyData error: Error: Request failed with status code 404
    at createError (/usr/local/lib/node_modules/homebridge-meraki-control/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-meraki-control/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-meraki-control/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  config: [Object],
  request: [ClientRequest],
  response: [Object],
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by magic7s** [comment]
Looks good, thanks!
